apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
    - name: todoapp
      image: kulyk404/kub2py
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5